image: python:3.9

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Backend build and test
build_backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t backend:latest ./backend
  artifacts:
    paths:
      - backend/
  only:
    - main

test_backend:
  stage: test
  script:
    - pip install -r backend/requirements.txt
    - python -m pytest backend/tests/
  allow_failure: true
  only:
    - main

# Frontend build and test
build_frontend:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/
  only:
    - main

test_frontend:
  stage: test
  image: node:16
  script:
    - cd frontend
    - npm install
    - npm test
  allow_failure: true
  only:
    - main

# Deployment
deploy:
  stage: deploy
  image: python:3.9
  script:
    - pip install -r backend/requirements.txt
    - cd backend
    - python app.py
  environment:
    name: production
    url: https://${CI_PROJECT_PATH_SLUG}.gitlab.io
  variables:
    FLASK_ENV: production
    FLASK_APP: app.py
    OPENAI_API_KEY: ${OPENAI_API_KEY}
    LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
  only:
    - main 